package proyecto_entornos;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a store that manages and records generated invoices.
 */
public class Tienda
{
    /*ATRIBUTOS*/
    private String nombre;
    private List<Factura> facturas;

    /**
     * Store constructor
     * @param nombre Store's trade name
     */
    public Tienda(String nombre)
    {
        this.nombre = nombre;
        this.facturas = new ArrayList<>();
    }

    /*GETTERS*/
    /**
     * Returns the store name.
     *
     * @return the store name
     */
    public String getNombre() 
    { 
        return nombre; 
    }

    /**
     * Returns the list of invoices generated by the store.
     *
     * @return the list of generated invoices
     */
    public List<Factura> getFacturas() 
    { 
        return facturas; 
    }

    /**
     * Main entry point orchestrating the complete sales workflow
     * Steps:
     * 1. Validates that the order is not empty
     * 2. Calculates the gross order subtotal
     * 3. Breaks down VAT and shipping costs
     * 4. Applies the customer loyalty discount
     * 5. Generates and records the invoice
     * @param cliente The customer making the purchase
     * @param pedido The order containing the list of products
     * @return The generated invoice with the full breakdown
     * @throws IllegalArgumentException if the customer or order is null
     * @throws IllegalStateException if the order contains no products
     */
    public Factura realizarVenta(Cliente cliente, Pedidos pedido)
    {
        // Validaciones de entrada
        if (cliente == null)
        {
            throw new IllegalArgumentException("El cliente no puede ser nulo.");
        }
        if (pedido == null)
        {
            throw new IllegalArgumentException("El pedido no puede ser nulo.");
        }
        if (pedido.getProducto().isEmpty())
        {
            throw new IllegalStateException("No se puede procesar un pedido sin productos.");
        }

        // 1. Calcular totales desglosados
        double totalNeto = calcularTotalNeto(pedido);
        double totalIva = calcularTotalIva(pedido);
        double totalEnvio = calcularTotalEnvio(pedido, cliente.getPais());
        double subtotal = totalNeto + totalIva + totalEnvio;

        // 2. Aplicar descuento de fidelidad del cliente
        double porcentajeDescuento = cliente.calcularDescuentoFidelidad();
        double descuentoAplicado = subtotal * porcentajeDescuento;
        double totalFinal = subtotal - descuentoAplicado;

        // 3. Generar factura
        Factura factura = new Factura(totalNeto, totalIva, totalEnvio, descuentoAplicado, totalFinal, cliente.getNombre(), pedido.getIdPedido());

        // 4. Registrar la factura en el historial de la tienda
        facturas.add(factura);
        return factura;
    }

    /**
     * Calculates the sum of the base prices of all products
     * @param order Order containing the products
     * @return Net total excluding taxes
     */
    private double calcularTotalNeto(Pedidos pedido)
    {
        double neto = 0;
        for (Producto p : pedido.getProducto())
        {
            neto += p.getPrecio();
        }
        return neto;
    }

    /**
     * Calculates the total VAT amount for the digital products in the order
     * VAT is not applied to physical products in this method
     * @param pedido Order containing the products
     * @return Total VAT amount
     */
    private double calcularTotalIva(Pedidos pedido)
    {
        double totalIva = 0;
        for (Producto p : pedido.getProducto())
        {
            if (p instanceof ProductoDigital)
            {
                ProductoDigital pd = (ProductoDigital) p;
                totalIva += pd.calcularPrecioFinal() - pd.getPrecio();
            }
        }
        return totalIva;
    }

    /**
     * Calculates the total shipping cost for the physical products in the order
     * The cost depends on the customer's country
     * @param pedido Order containing the products
     * @param paisCliente Destination country for the shipment
     * @return Total shipping cost
     */
    private double calcularTotalEnvio(Pedidos pedido, String paisCliente)
    {
        double totalEnvio = 0;
        String pais = (paisCliente != null) ? paisCliente : "España";

        for (Producto p : pedido.getProducto())
        {
            if (p instanceof ProductoFisico)
            {
                ProductoFisico pf = (ProductoFisico) p;
                totalEnvio += pf.calcularCosteEnvio(pais);
            }
        }
        return totalEnvio;
    }
}